### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by ddugovic** [danibarker/WordSmith#4]
Presently the process consumes 413M (VIRT) 333M (RES) of memory.  Perhaps loading the words into a database could reduce memory usage.

Current workaround: comment out command "lexicon" and only load the CSW dictionary.

**Comment by danibarker** [comment]
SQLite an option for a db that could be packaged with the bot?

**Comment by danibarker** [comment]
Looking at PySQLite.  Might give it a try to see how well that works

**Comment by danibarker** [comment]
Looks like APSW would be better than PySQLite

**Comment by ddugovic** [comment]
Ah, cool.  This is a low-priority issue since presently I'm only loading CSW, but other players using cloud-hosted instances with limited memory might care.  But maybe next holiday I'll try APSW.

**Comment by andy-k** [comment]
it doesn't seem that using a database would help reduce memory usage.

here are some ideas to reduce memory usage:
- use `mmap`. it's ok to close the file, just keep the mmap open. `with open('csw.dat', 'rb') as f: m = mmap.mmap(f.fileno(), 0, access=mmap.ACCESS_READ)`, then outside the `with` just use `m`. pages are read and cached as needed by the OS. (note: empty files need special-casing.)
- work with bytes, not strings, wherever possible. `'a'.encode()` and `b'a'.decode()` to convert between them.
- load only the words, don't load definitions.
- a word found in both csw and nwl should be stored in memory just once.
- store each unique word once in a sorted list. refer to them by index everywhere else. (because `word[i] < word[j]` implies `i < j`, sorting/searching can be done without comparing the words.)
- use typed arrays (`array.array`) to remove per-element overhead.
- for each lexicon and each word, remember the file position (use `m.tell()` before `m.readline()`). to iterate lines do `for l in iter(m.readline, b''): a=l.rstrip().split(b'\t')`. (specifically, make two typed arrays for each lexicon, one giving the index to the word in the combined list, and the other giving the byte position of the detailed line within the file.)
- definitions, hooks, probabilities can be reread as needed, just seek and readline the mmap. `m.seek(known_file_position); a=m.readline().rstrip().split(b'\t')`.
- octothorps can be implied by checking if a word is in the other lexicon. that same functionality can support `luved$` too. so `csw#` need not be a separate thing from `csw`. (use `bisect.bisect_left` and find the word index in the other lexicon's typed array of valid word indexes, see the `def index` in the `bisect` documentation.)
- generally instead of dict, consider using sorted lists. use `bisect` to do lookups. dicts tend to use more memory and they're slower to iterate.
- most queries can `break` early instead of first building a full array of all matches only to report the first few.

some data structures are needed to support anagram queries. memory for this may become available when the above optimizations are applied:
- consider building a dawg (this would make anagrams fast, almost obviate hooks, enable subanagrams/steals, etc).
- alternatively, build a trie mapping alphagrams to a list of matching words. (this larger structure only supports anagram.) to stably keep the first few alphabetical matches, use `heapq`.

hope that makes sense 😄

**Comment by ddugovic** [comment]
Nice, I'll try `mmap`.  My goal is being able to host both my discord bot and my twitch bot from a low-cost, non-AWS cloud (e.g. OVH) so anyone could do the same, so I would be surprised if a database (which both bots could connect to) would increase memory usage... but `mmap` is far easier to code.

**Comment by ddugovic** [comment]
I did wonder about this... that makes sense (if you have multiple dictionaries loaded):

- octothorps can be implied by checking if a word is in the other lexicon. that same functionality can support luved$ too. so csw# need not be a separate thing from csw. (use bisect.bisect_left and find the word index in the other lexicon's typed array of valid word indexes, see the def index in the bisect documentation.)

**Comment by danibarker** [comment]
@ddugovic added you as a collaborator so you can just merge changes yourself if you like

**Comment by ddugovic** [comment]
Latest `master` now uses `mmap` so it no longer consumes 1GB of memory.  Thanks all for the suggestions.
